config/routes.rb
Rails.application.routes.draw do

  mount ShopifyApp::Engine, at: '/'
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  root :to => 'home#index'

  resources :application_charges, only: [:index, :create] do
    member do
      post :activate
    end
  end

  resource :recurring_application_charge, only: [:show, :create, :destroy] do
    collection do
      get :callback
      post :customize
    end
  end

  resource :usage_charge, only: [:show, :create]

  resource :application_credit, only: [:show, :create, :index]
end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/controllers/application_charges_controller.rb
class ApplicationChargesController < AuthenticatedController

  def index
    @application_charges = ShopifyAPI::ApplicationCharge.all || []
  end

  def create
    application_charge = ShopifyAPI::ApplicationCharge.new(params[:application_charge])
    application_charge.test = true
    application_charge.return_url = application_charges_url

    if application_charge.save
      flash[:success] = "One-time charge was successfully created"
      fullpage_redirect_to application_charge.confirmation_url
    else
      flash[:danger] = application_charge.errors.full_messages.first.to_s.capitalize
      redirect_to application_charges_path
    end
  end

  def activate
    application_charge = ShopifyAPI::ApplicationCharge.find(params[:id])
    if application_charge.activate
      flash[:success] = "One-time charge has been activated"
    end

    redirect_to application_charges_path
  end

  private

  def application_charge_params
    params.require(:application_charge).permit(
      :name,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_credits_controller.rb
class ApplicationCreditsController < AuthenticatedController

  def show
    @application_credits = ShopifyAPI::ApplicationCredit.all
  end

  def create
    application_credit = ShopifyAPI::ApplicationCredit.new(application_credit_params)
    application_credit.test = true

    if application_credit.save
      flash[:success] = "Application credit was issued successfully"
    else
      flash[:danger] = application_credit.errors.full_messages.to_sentence
    end

    redirect_to application_credit_path
  end

  private

  def application_credit_params
    params.require(:application_credit).permit(
      :description,
      :amount
    )
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  include ShopifyApp::LoginProtection
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
end

app/controllers/recurring_application_charges_controller.rb
class RecurringApplicationChargesController < AuthenticatedController

  before_action :load_current_recurring_charge

  def show
  end

  def create
    @recurring_application_charge.try!(:cancel)

    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.new(recurring_application_charge_params)
    @recurring_application_charge.test = true
    @recurring_application_charge.return_url = callback_recurring_application_charge_url

    if @recurring_application_charge.save
      fullpage_redirect_to @recurring_application_charge.confirmation_url
    else
      flash[:danger] = @recurring_application_charge.errors.full_messages.first.to_s.capitalize
      redirect_to_correct_path(@recurring_application_charge)
    end
  end

  def customize
    @recurring_application_charge.customize(params[:recurring_application_charge])
    fullpage_redirect_to @recurring_application_charge.update_capped_amount_url
  end

  def callback
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.find(params[:charge_id])
    if @recurring_application_charge.status == 'accepted'
      @recurring_application_charge.activate
    end

    redirect_to_correct_path(@recurring_application_charge)
  end

  def destroy
    @recurring_application_charge.cancel

    flash[:success] = "Recurring application charge was cancelled successfully"

    redirect_to_correct_path(@recurring_application_charge)
  end

  private

  def load_current_recurring_charge
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.current
  end

  def recurring_application_charge_params
    params.require(:recurring_application_charge).permit(
      :name,
      :price,
      :capped_amount,
      :terms,
      :trial_days
    )
  end

  def redirect_to_correct_path(recurring_application_charge)
    if recurring_application_charge.try(:capped_amount)
      redirect_to usage_charge_path
    else
      redirect_to recurring_application_charge_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/controllers/usage_charges_controller.rb
class UsageChargesController < AuthenticatedController

  def show
    @recurring_application_charge = ShopifyAPI::RecurringApplicationCharge.current
    @usage_charges = @recurring_application_charge.usage_charges if @recurring_application_charge.try(:capped_amount)
  end

  def create
    usage_charge = ShopifyAPI::UsageCharge.new(params[:usage_charge])
    usage_charge.prefix_options[:recurring_application_charge_id] = ShopifyAPI::RecurringApplicationCharge.current.id

    if usage_charge.save
      flash[:success] = "Usage charge was created successfully"
    else
      flash[:danger] = usage_charge.errors.full_messages.first.to_s.capitalize
    end

    redirect_to usage_charge_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_balance_warning?(charge)
    (charge.balance_used.to_f / charge.capped_amount.to_f) > 0.6
  end

  def balance_used_percentage(charge)
    (charge.balance_used.to_f / charge.capped_amount.to_f) * 100
  end
end

app/views/application_charges/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "One-time Charge",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="section">
  <div class= "section_left col-md-3">
    <h4>
      One-time Charge
    </h4>
    <p>
      Create a new one-time charge
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="section_right">

          <%= form_tag(application_charges_path, method: 'post', class: "form") do %>
            <div class="form-group">
              <%= label_tag 'text', 'Name' %>
              <%= text_field_tag 'application_charge[name]', nil, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= label_tag 'number', 'Price' %>
              <%= number_field_tag 'application_charge[price]', nil, class: 'form-control', step: 0.01 %>
            </div>

            <%= submit_tag "Create Charge", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

    <% if @application_charges.any? %>
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <% @application_charges.each do |charge| %>
                <tr>
                  <td>
                    <%= charge.name %>
                  </td>
                  <td>
                    $<%= charge.price %>
                  </td>
                  <td>
                    <% if charge.status == 'accepted' %>
                      <%= link_to 'Activate charge', activate_application_charge_path(id: charge.id), method: :post %>
                    <% else %>
                      <span class="badge">
                        <%= charge.status.capitalize %>
                      </span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/application_credits/show.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Application Credit",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Application Credit
    </h4>
    <p>
      Create a new application credit
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_tag(application_credit_path, method: 'post', class: "form") do %>
          <div class="form-group">
            <%= label_tag 'text', 'Description' %>
            <%= text_field_tag 'application_credit[description]', nil, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= label_tag 'number', 'Amount' %>
            <%= number_field_tag 'application_credit[amount]', nil, class: 'form-control', step: 0.01 %>
          </div>

          <%= submit_tag "Issue Credit", class: "btn btn-primary" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

<% if @application_credits.try!(:any?) %>
  <div class="section">
    <div class= "col-md-3">
      <h4>
        Issued Credits
      </h4>

      <p>
        Here you can see the description and amount
      </p>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Description</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @application_credits.each do |application_credit| %>
                <tr>
                  <td>
                    <%= application_credit.description %>
                  </td>
                  <td>
                    $<%= application_credit.amount %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });
  </script>
<% end %>

<div class="section">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h4>One-time charges</h4>
        <%= link_to 'Charge using one time charges', application_charges_path, class: 'btn btn-large' %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h4>Recurring charges</h4>
        <%= link_to 'Charge using recurring charges', recurring_application_charge_path, class: 'btn btn-large' %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h4>Usage charges</h4>
        <%= link_to 'Charge using usage charges', usage_charge_path, class: 'btn btn-large' %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h4>Application credits</h4>
        <%= link_to 'Issue application credits', application_credit_path, class: 'btn btn-large' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillingTestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name.presence || 'Embedded Shopify App Example' %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/recurring_application_charges/show.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Recurring Charge",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @recurring_application_charge.present? && !@recurring_application_charge.try(:capped_amount) %>
  <div class="section">
    <div class= "col-md-3">
      <h4>
        Recurring Charge
      </h4>

      <p>
        Here you can see the terms of the recurring charge.
      </p>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Trial Days</th>
                <th>Billing On</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%= @recurring_application_charge.name %>
                </td>
                <td>
                  $<%= @recurring_application_charge.price %>
                </td>
                <td>
                  <%= @recurring_application_charge.trial_days %>
                </td>
                <td>
                  <%= @recurring_application_charge.billing_on %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <hr />

  <div class="section">
    <div class= "col-md-3">
    </div>
    <div class="col-md-9">
      <p>
        <%= link_to 'Cancel charge', recurring_application_charge_path, method: :delete, class: "btn btn-danger" %>
      </p>
    </div>
  </div>

<% else %>
  <div class="section">
    <div class= "col-md-3">
      <h4>
        Recurring Application Charge
      </h4>
      <p>
        Create a new recurring application charge
      </p>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_tag(recurring_application_charge_path, method: 'post', class: "form") do %>
            <div class="form-group">
              <%= label_tag 'text', 'Name' %>
              <%= text_field_tag 'recurring_application_charge[name]', nil, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= label_tag 'number', 'Price' %>
              <%= number_field_tag 'recurring_application_charge[price]', nil, class: 'form-control', step: 0.01 %>
            </div>

            <div class="form-group">
              <%= label_tag 'number', 'Trial Days' %>
              <%= number_field_tag 'recurring_application_charge[trial_days]', nil, class: 'form-control' %>
            </div>

            <%= submit_tag "Create Charge", class: "btn btn-primary" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/usage_charges/show.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Usage Charge",
      icon: "<%= asset_path('favicon.png') %>"
    });
  });
</script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if @recurring_application_charge.present? && @recurring_application_charge.try(:capped_amount) %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Recurring charge
    </h4>

    <p>
      Here you can see the terms of the recurring charge and the remaining balance.
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
           <div class="col-md-6">Total Usage Charges</div>
           <div class="col-md-6"><span class="pull-right">
            $<%= @recurring_application_charge.balance_used %> /
            $<%= @recurring_application_charge.capped_amount.to_f %>
           </span></div>
        </div>
        <div class="progress progress-usage" define="{ percentage: <%= balance_used_percentage(@recurring_application_charge) %> }">
          <div class="progress-bar" role="progressbar" aria-valuenow="<%= balance_used_percentage(@recurring_application_charge) %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= balance_used_percentage(@recurring_application_charge) %>%" bind-class="{ 'progress-bar-warning': (percentage > 60 && percentage <= 80), 'progress-bar-danger': percentage  > 80  }">
          </div>
        </div>

        <div define="{ increaseCap: false, showLink: <%= show_balance_warning?(@recurring_application_charge) %> }">
          <%= form_tag(customize_recurring_application_charge_path, method: 'post', class: "form-inline", "bind-show" => "increaseCap") do %>
            <div class="form-group">
              <%= label_tag 'number', 'New capped amount' %>
              <%= number_field_tag 'recurring_application_charge[capped_amount]', @recurring_application_charge.capped_amount.to_f * 2, class: 'form-control', step: 0.01 %>
            </div>

            <%= submit_tag "Update Capped Amount", class: "btn btn-primary" %>
          <% end %>

          <p bind-show="!increaseCap && showLink">
            You are reaching the maximum amount of usage fees this month.
            <a bind-event-click="increaseCap = true">Increase capped amount</a>
          </p>
        </div>

      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Capped Amount</th>
              <th>Balance Remaining</th>
              <th>Billing On</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= @recurring_application_charge.name %>
              </td>
              <td>
                $<%= @recurring_application_charge.price %>
              </td>
              <td>
                $<%= @recurring_application_charge.capped_amount.to_f %>
              </td>
              <td>
                $<%= @recurring_application_charge.balance_remaining %>
              </td>
              <td>
                <%= @recurring_application_charge.billing_on %>
              </td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<hr>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Usage Charge
    </h4>
    <p>
      Create new usage charges
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">

        <%= form_tag(usage_charge_path, method: 'post', class: "form-inline") do %>

        <div class="form-group">
          <%= label_tag 'number', 'Price' %>
          <%= number_field_tag 'usage_charge[price]', nil, class: 'form-control', step: 0.01 %>
        </div>

        <div class="form-group">
          <%= label_tag 'text', 'Description' %>
          <%= text_field_tag 'usage_charge[description]', nil, class: 'form-control' %>
        </div>

          <%= submit_tag "Create Charge", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <% if @usage_charges.try!(:any?) %>
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Description</th>
                <th>Price</th>
                <th>Billing On</th>
              </tr>
            </thead>
            <tbody>
              <% @usage_charges.to_a.reverse.each do |charge| %>
                <tr>
                  <td>
                    <%= charge.description %>
                  </td>
                  <td>
                    $<%= charge.price %>
                  </td>
                  <td>
                    <%= charge.billing_on %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

<hr />

<div class="section">
  <div class= "col-md-3">
  </div>
  <div class="col-md-9">
    <p>
      <%= link_to 'Cancel charge', recurring_application_charge_path, method: :delete, class: "btn btn-danger" %>
    </p>
  </div>
</div>


<% else %>

<div class="section">
  <div class= "col-md-3">
    <h4>
      Recurring charge
    </h4>

    <p>
      Create a new recurring charge with a capped amount.
    </p>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div bind-show="!showCreateForm">
          <%= form_tag(recurring_application_charge_path, method: 'post', class: "form") do %>
            <div class="form-group">
              <%= label_tag 'text', 'Name' %>
              <%= text_field_tag 'recurring_application_charge[name]', nil, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= label_tag 'number', 'Price' %>
              <%= number_field_tag 'recurring_application_charge[price]', nil, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= label_tag 'number', 'Capped Amount'%>
              <%= number_field_tag 'recurring_application_charge[capped_amount]', nil, class: 'form-control', step: 0.01%>
            </div>

            <div class="form-group">
              <%= label_tag 'text', 'Terms' %>
              <%= text_field_tag 'recurring_application_charge[terms]', nil, class: 'form-control' %>
            </div>

            <%= submit_tag "Create Charge", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>